name: Destroy Bastion VM

on:
  workflow_dispatch:  # Manually trigger from GitHub Actions UI

jobs:
  destroy-vm:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Install gcloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: "your-gcp-project-id"

    - name: Destroy Bastion VM
      run: |
        gcloud compute instances delete bastion-host --zone=us-central1-a --quiet
